spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: first-id
      auto-offset-reset: earliest

# https://velog.io/@shinmj1207/Apache-Kafka-Docker-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-Spring-boot-Kafka-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0
